#### Importing The Library's

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

#### Reading CSV Files

In [2]:
df = pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

C:\Users\venkatraman.b\AppData\Local\Temp\ipykernel_1624\569291826.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("TWO_CENTURIES_OF_UM_RACES.csv")

#### Displaying The First Five Data's In The CSV File

In [3]:
df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

#### Checking The Shape of the CSV File

In [4]:
df.shape

(7461195, 13)

#### Checking the data types in csv files

In [5]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

#### Getting the data only contain 50 KM and 50 Mile in the year 2020

In [6]:
year_2020 = df[(df["Event distance/length"].isin(["50km","50mi"])) & (df["Year of event"] == 2020)]
year_2020.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
2538571,2020,07.-09.02.2020,Taipei 48hr Ultra Marathon - 50mi (TPE),50mi,38,7:34:19 h,日本隊,JPN,1965.0,M,M50,10.627,53107
2538572,2020,07.-09.02.2020,Taipei 48hr Ultra Marathon - 50mi (TPE),50mi,38,7:43:50 h,NaN,AUS,1974.0,M,M45,10.409,8785
2538573,2020,07.-09.02.2020,Taipei 48hr Ultra Marathon - 50mi (TPE),50mi,38,8:04:40 h,NaN,TPE,1976.0,M,M40,9.962,4502
2538574,2020,07.-09.02.2020,Taipei 48hr Ultra Marathon - 50mi (TPE),50mi,38,8:30:49 h,台灣大腳ㄚ長跑協會,TPE,1969.0,F,W50,9.452,63964
2538575,2020,07.-09.02.2020,Taipei 48hr Ultra Marathon - 50mi (TPE),50mi,38,8:34:47 h,NaN,TPE,1964.0,M,M55,9.379,4485

#### Splitting The Event name column and seperating the country's from the result

##### Spliting the country name

In [7]:
country_names = df["Event name"].str.split("(").str.get(1).str.split(")").str.get(0)
country_names

0          CHI
1          CHI
2          CHI
3          CHI
4          CHI
          ...
7461190    FRA
7461191    FRA
7461192    HUN
7461193    HUN
7461194    HUN
Name: Event name, Length: 7461195, dtype: object

In [8]:
country_names == "USA"

0          False
1          False
2          False
3          False
4          False
           ...
7461190    False
7461191    False
7461192    False
7461193    False
7461194    False
Name: Event name, Length: 7461195, dtype: bool

#### Combining both the logic and Displaying the result

In [9]:
df[(df["Event distance/length"].isin(["50km","50mi"])) & (df["Year of event"] == 2020) & (df["Event name"].str.split("(").str.get(1).str.split(")").str.get(0) == "USA")]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,3:17:55 h,"*Normandy Park, WA",USA,1991.0,M,M23,15.158,71287
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:02:32 h,"*Gold Bar, WA",USA,1981.0,M,M35,12.369,629508
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:07:57 h,"*Vashon, WA",USA,1999.0,M,MU23,12.099,64838
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:22:02 h,"*Gig Harbor, WA",USA,1983.0,M,M35,11.449,704450
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:27:34 h,"*Bainbridge Island, WA",USA,1977.0,M,M40,11.212,810281
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2760957,2020,03.10.2020,Yankee Springs Fall Trail Run Festival (USA),50km,30,7:07:48 h,"*East Lansing, MI",USA,1958.0,F,W60,7.013,816361
2760958,2020,03.10.2020,Yankee Springs Fall Trail Run Festival (USA),50km,30,7:27:22 h,"*Traverse City, MI",USA,1977.0,F,W40,6.706,326469
2760959,2020,03.10.2020,Yankee Springs Fall Trail Run Festival (USA),50km,30,7:27:24 h,"*Traverse City, MI",USA,1962.0,F,W55,6.705,372174
2760960,2020,03.10.2020,Yankee Springs Fall Trail Run Festival (USA),50km,30,7:38:30 h,"*Mason, MI",USA,1981.0,F,W35,6.543,860349
2760961,2020,03.10.2020,Yankee Springs Fall Trail Run Festival (USA),50km,30,7:59:53 h,NaN,USA,1980.0,M,M35,6.252,770097

In [10]:
df2 = df[(df["Event distance/length"].isin(["50km","50mi"])) & (df["Year of event"] == 2020) & (df["Event name"].str.split("(").str.get(1).str.split(")").str.get(0) == "USA")]
df2.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,3:17:55 h,"*Normandy Park, WA",USA,1991.0,M,M23,15.158,71287
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:02:32 h,"*Gold Bar, WA",USA,1981.0,M,M35,12.369,629508
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:07:57 h,"*Vashon, WA",USA,1999.0,M,MU23,12.099,64838
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:22:02 h,"*Gig Harbor, WA",USA,1983.0,M,M35,11.449,704450
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition (USA),50km,20,4:27:34 h,"*Bainbridge Island, WA",USA,1977.0,M,M40,11.212,810281

#### Displaying the shape of df2 Dataframe

In [11]:
df2.shape

(26090, 13)

#### Removing country name in Event Name column

In [12]:
df2["Event name"].str.split("(").str.get(0)

2539945    West Seattle Beach Run - Winter Edition
2539946    West Seattle Beach Run - Winter Edition
2539947    West Seattle Beach Run - Winter Edition
2539948    West Seattle Beach Run - Winter Edition
2539949    West Seattle Beach Run - Winter Edition
                             ...
2760957     Yankee Springs Fall Trail Run Festival
2760958     Yankee Springs Fall Trail Run Festival
2760959     Yankee Springs Fall Trail Run Festival
2760960     Yankee Springs Fall Trail Run Festival
2760961     Yankee Springs Fall Trail Run Festival
Name: Event name, Length: 26090, dtype: object

In [13]:
df2["Event name"] = df2["Event name"].str.split("(").str.get(0)

C:\Users\venkatraman.b\AppData\Local\Temp\ipykernel_1624\3464257636.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Event name"] = df2["Event name"].str.split("(").str.get(0)

In [14]:
df2.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,3:17:55 h,"*Normandy Park, WA",USA,1991.0,M,M23,15.158,71287
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:02:32 h,"*Gold Bar, WA",USA,1981.0,M,M35,12.369,629508
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:07:57 h,"*Vashon, WA",USA,1999.0,M,MU23,12.099,64838
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:22:02 h,"*Gig Harbor, WA",USA,1983.0,M,M35,11.449,704450
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:27:34 h,"*Bainbridge Island, WA",USA,1977.0,M,M40,11.212,810281

#### Calculating the Athelet age for 2025

In [15]:
df2["Athelet_Age"] = 2025 - df2["Athlete year of birth"]
df2["Athelet_Age"].head()

C:\Users\venkatraman.b\AppData\Local\Temp\ipykernel_1624\640266928.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Athelet_Age"] = 2025 - df2["Athlete year of birth"]

2539945    34.0
2539946    44.0
2539947    26.0
2539948    42.0
2539949    48.0
Name: Athelet_Age, dtype: float64

#### Removing h from Athelet perfomance column

In [16]:
df2["Athlete performance"] = df2["Athlete performance"].str.split('h').str.get(0)
df2.head()

C:\Users\venkatraman.b\AppData\Local\Temp\ipykernel_1624\3096109847.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Athlete performance"] = df2["Athlete performance"].str.split('h').str.get(0)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID,Athelet_Age
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,3:17:55,"*Normandy Park, WA",USA,1991.0,M,M23,15.158,71287,34.0
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:02:32,"*Gold Bar, WA",USA,1981.0,M,M35,12.369,629508,44.0
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:07:57,"*Vashon, WA",USA,1999.0,M,MU23,12.099,64838,26.0
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:22:02,"*Gig Harbor, WA",USA,1983.0,M,M35,11.449,704450,42.0
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:27:34,"*Bainbridge Island, WA",USA,1977.0,M,M40,11.212,810281,48.0

#### Droping unwanted columns in the dataset

##### Dropping these columns : Athlete club, Athlete country, Athlete year of birth, Athlete age category

In [17]:
df2 = df2.drop(["Athlete club","Athlete country","Athlete year of birth","Athlete age category"], axis = 1)

In [18]:
df2.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athelet_Age
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,3:17:55,M,15.158,71287,34.0
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:02:32,M,12.369,629508,44.0
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:07:57,M,12.099,64838,26.0
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:22:02,M,11.449,704450,42.0
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:27:34,M,11.212,810281,48.0

#### Dropping na values from the dataset

In [19]:
df2.isna().sum()

Year of event                  0
Event dates                    0
Event name                     0
Event distance/length          0
Event number of finishers      0
Athlete performance            0
Athlete gender                 0
Athlete average speed          0
Athlete ID                     0
Athelet_Age                  233
dtype: int64

In [20]:
df2 = df2.dropna()

In [21]:
df2.isna().sum()

Year of event                0
Event dates                  0
Event name                   0
Event distance/length        0
Event number of finishers    0
Athlete performance          0
Athlete gender               0
Athlete average speed        0
Athlete ID                   0
Athelet_Age                  0
dtype: int64

#### Checking the duplicate values in dataset

In [22]:
df2[df2.duplicated() == True]

Empty DataFrame
Columns: [Year of event, Event dates, Event name, Event distance/length, Event number of finishers, Athlete performance, Athlete gender, Athlete average speed, Athlete ID, Athelet_Age]
Index: []

#### Reseting the Index

In [23]:
df2.reset_index(drop = True)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete gender,Athlete average speed,Athlete ID,Athelet_Age
0,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,3:17:55,M,15.158,71287,34.0
1,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:02:32,M,12.369,629508,44.0
2,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:07:57,M,12.099,64838,26.0
3,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:22:02,M,11.449,704450,42.0
4,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:27:34,M,11.212,810281,48.0
...,...,...,...,...,...,...,...,...,...,...
25852,2020,03.10.2020,Yankee Springs Fall Trail Run Festival,50km,30,7:07:48,F,7.013,816361,67.0
25853,2020,03.10.2020,Yankee Springs Fall Trail Run Festival,50km,30,7:27:22,F,6.706,326469,48.0
25854,2020,03.10.2020,Yankee Springs Fall Trail Run Festival,50km,30,7:27:24,F,6.705,372174,63.0
25855,2020,03.10.2020,Yankee Springs Fall Trail Run Festival,50km,30,7:38:30,F,6.543,860349,44.0
25856,2020,03.10.2020,Yankee Springs Fall Trail Run Festival,50km,30,7:59:53,M,6.252,770097,45.0

#### Reframeing the data types

In [24]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete gender                object
Athlete average speed         object
Athlete ID                     int64
Athelet_Age                  float64
dtype: object

In [25]:
df2["Athlete average speed"] = df2["Athlete average speed"].astype(float)

In [26]:
df2.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete gender                object
Athlete average speed        float64
Athlete ID                     int64
Athelet_Age                  float64
dtype: object

#### Renaming the column names

In [27]:
df2 = df2.rename(columns = {'Year of event':'Year',
                 'Event dates':'Race_day',
                 'Event name':'Race_name',
                 'Event distance/length':'Event_distance/length',
                 'Event number of finishers':'Finisher_count',
                 'Athlete performance':'Athlete_performance',
                 'Athlete gender': 'Athlete_gender',
                 'Athlete average speed':'Athlete_average_speed',
                 'Athlete ID':'Athlete_ID',
                 'Athelet_Age':'Athelet_Age'})

In [29]:
df2.head()

,Year,Race_day,Race_name,Event_distance/length,Finisher_count,Athlete_performance,Athlete_gender,Athlete_average_speed,Athlete_ID,Athelet_Age
2539945,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,3:17:55,M,15.158,71287,34.0
2539946,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:02:32,M,12.369,629508,44.0
2539947,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:07:57,M,12.099,64838,26.0
2539948,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:22:02,M,11.449,704450,42.0
2539949,2020,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,4:27:34,M,11.212,810281,48.0

#### Reordering the column

In [30]:
df3 = df2[['Race_day','Race_name','Event_distance/length','Finisher_count','Athlete_ID','Athlete_gender','Athlete_performance','Athlete_average_speed','Athelet_Age','Year']]

In [31]:
df3.head()

,Race_day,Race_name,Event_distance/length,Finisher_count,Athlete_ID,Athlete_gender,Athlete_performance,Athlete_average_speed,Athelet_Age,Year
2539945,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,71287,M,3:17:55,15.158,34.0,2020
2539946,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,629508,M,4:02:32,12.369,44.0,2020
2539947,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,64838,M,4:07:57,12.099,26.0,2020
2539948,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,704450,M,4:22:02,11.449,42.0,2020
2539949,02.02.2020,West Seattle Beach Run - Winter Edition,50km,20,810281,M,4:27:34,11.212,48.0,2020

#### Finding the races from Everglades

In [38]:
df3[df3["Race_name"] == "Everglades 50 Mile Ultra Run "].head()

,Race_day,Race_name,Event_distance/length,Finisher_count,Athlete_ID,Athlete_gender,Athlete_performance,Athlete_average_speed,Athelet_Age,Year
2591476,14.03.2020,Everglades 50 Mile Ultra Run,50mi,40,820757,M,8:31:39,9.436,32.0,2020
2591477,14.03.2020,Everglades 50 Mile Ultra Run,50mi,40,46432,M,8:31:48,9.433,44.0,2020
2591478,14.03.2020,Everglades 50 Mile Ultra Run,50mi,40,813617,M,8:34:43,9.380,39.0,2020
2591479,14.03.2020,Everglades 50 Mile Ultra Run,50mi,40,820758,M,9:07:35,8.817,38.0,2020
2591480,14.03.2020,Everglades 50 Mile Ultra Run,50mi,40,647115,M,9:15:32,8.691,35.0,2020